#!/bin/sh

set -eu

files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.swift' | tr '\n' ' ')

if [ -z "$files" ]; then
  exit 0
fi

make format FILES="$files"
make lint FILES="$files"
git add $files